# Generated by Django 3.1.1 on 2021-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrawlNotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placements_1',
            name='Placement',
            field=models.CharField(max_length=7),
        ),
        migrations.DeleteModel(
            name='Characters_1',
        ),
    ]
